name: fastapi
app: python@3.11
options:
  ports: 8000
  start: uvicorn main:app --host=0.0.0.0 --port=8000
context:
  git:
    url: https://github.com/riverSun1/recommend-movie-web-backend.git
    branch: main
  preset: python-fastapi