image: python:3.9

on:
  release:
    types: [created]

variables:
  IMAGE_VERSION: v1.0.0
  WORK_DIR: .
  NODE_ENV: development
  DOCKER_DRIVER: overlay2
  DOCKER_FILE: Dockerfile
  DOCKER_BUILD_CONTEXT: .
  DOCKER_IMAGE: recommend-movie-web:${IMAGE_VERSION}
cache:
  key: "$CI_COMMIT_REF_SLUG"
stages:
  - deploy
Deploy:
  stage: deploy
  only:
    - deploy
  tags:
    - recommend-movie-web
  script:
    - docker stop $(docker ps -aq) || true
    - docker build -t ${DOCKER_IMAGE} .
    - docker run -it -d -p 8080:80 --restart=unless-stopped ${DOCKER_IMAGE}
